### ISSUE TITLE
java.lang.UnsatisfiedLinkError when restarting the module

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/kamon-system-metrics#21]
The exception bellow happens when `startCollecting` is called several times on the same JVM. This is especially common when running a Play application on development mode because all modules are constantly restarted on every change.

```
WARNING: Sigar library is already provisioned.
[error] (run-main-2) java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Sigar.getNativeVersion()Ljava/lang/String;
[error] java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Sigar.getNativeVersion()Ljava/lang/String;
[error]     at org.hyperic.sigar.Sigar.getNativeVersion(Native Method)
[error]     at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:101)
[error]     at kamon.system.package$.sigar$lzycompute(package.scala:25)
[error]     at kamon.system.package$.kamon$system$package$$sigar(package.scala:25)
[error]     at kamon.system.package$MetricBuilder.register(package.scala:36)
[error]     at kamon.system.host.SigarMetricsUpdater.<init>(SigarMetricsUpdater.scala:27)
[error]     at kamon.system.SystemMetrics$.collectSigarMetrics(SystemMetrics.scala:89)
[error]     at kamon.system.SystemMetrics$.startCollecting(SystemMetrics.scala:72)
[error]     at com.codacy.worker.api.server.Server$.$anonfun$kamonTracer$2(Server.scala:62)
[error]     at scala.util.Try$.apply(Try.scala:213)
[error]     at com.codacy.worker.api.server.Server$.kamonTracer(Server.scala:59)
[error]     at com.codacy.worker.api.server.Server$.main(Server.scala:31)
[error]     at com.codacy.worker.api.server.Server.main(Server.scala)
[error]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:498)
[error]     at kamon.aspectj.sbt.SbtAspectJRunner$RunWithAspectJ.invokeMain(SbtAspectJRunner.scala:124)
[error]     at kamon.aspectj.sbt.SbtAspectJRunner$RunWithAspectJ.run0(SbtAspectJRunner.scala:108)
[error]     at kamon.aspectj.sbt.SbtAspectJRunner$RunWithAspectJ.execute$1(SbtAspectJRunner.scala:98)
[error]     at kamon.aspectj.sbt.SbtAspectJRunner$RunWithAspectJ.$anonfun$run$2(SbtAspectJRunner.scala:101)
[error]     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
```

**Comment by ivantopo** [comment]
Closing this as outdated, we are not using Sigar anymore.
